# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: prankshadow
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: serverless-storeit
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-storeit

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  environment:
    STAGE: ${env:STAGE, "prod"}
    JWT_SECRET: ${env:JWT_SECRET, "prod"}
  iam:
    role:
      name: serverless-my-ssm-role-storeit-${env:STAGE, "prod"}
      statements:
        - Effect: "Allow"
          Resource: "*"
          Action:
            - "ssm:GetParameter"
            - "ssm:GetParameters"
            - "ssm:GetParametersByPath"
            - "ssm:GetParameterHistory"
            - "ssm:DescribeParameters"

functions:
  graphql:
    handler: index.graphqlHandler
    events:
      - httpApi: "*"

plugins:
  - serverless-offline
